name: cataract_surgery_note
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+6

environment:
  sdk: ^3.10.1

dependencies:
  drift: ^2.34.0
  drift_flutter: ^0.3.0
  file_picker: ^11.0.2
  flutter:
    sdk: flutter
  flutter_riverpod: ^3.3.2
  intl: ^0.20.3
  path: ^1.9.1
  path_provider: ^2.1.6
  uuid: ^4.5.3
  video_player: ^2.11.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

hooks:
  user_defines:
    sqlite3:
      source: system
      name: sqlite3
